# Generated by Django 6.0.2 on 2026-03-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='prior_knowledge',
            field=models.FloatField(default=0.7),
        ),
    ]
